# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

NDRindex <- function(A, n, m) {
    .Call('_NDRindex_NDRindex', PACKAGE = 'NDRindex', A, n, m)
}

